# Use an official OpenJDK base image
FROM openjdk:17-jdk-slim

  # Set the working directory inside the container
WORKDIR /app

  # Copy the JAR file into the container
COPY target/ *.jar app.jar
RUN ls -lrt

  # Expose the application's port (change if needed)
EXPOSE 8081
  # Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
  
